DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
  -- menu_item_id INTEGER REFERENCES menu_items(id) ON DELETE CASCADE
  -- quantity INTEGER,
  -- name VARCHAR(255) NOT NULL,
);
